site_name: Boats Animator
site_dir: bin/mkdocs
repo_url: https://github.com/charlielee/boats-animator
nav:
- Home: index.md
- Introduction:
  - System Requirements: introduction/system-requirements.md
  - License: introduction/license.md
- Features:
  - Export Video: features/export-video.md
  - Keyboard Shortcuts: features/keyboard-shortcuts.md
  - Launcher Window: features/launcher-window.md
  - Main Window: features/main-window.md
theme: readthedocs
extra_css: [css/custom.css]
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.tables
  - markdown.extensions.toc
